title: Liang Zeng
email: objczl@example.com
baseurl: ""
url: ""
twitter_username: objczl
github_username:  objczl

markdown: kramdown

defaults:
    -
     scope:
         path: ""
     values:
         author: Liang Zeng
         description: Developer
         lang: en
         base-url: "/"
    -
     scope:
         path: zh-cn
     values:
         author: 曾亮
         description: 开发者
         lang: zh-cn
         base-url: "/zh-cn/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
