title: Liang Zeng
email: objczl@example.com
description: >-
    I'm an iOS/macOS developer.
baseurl: ""
url: ""
twitter_username: objczl
github_username:  objczl

markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
